#ifndef __CONTROL_FLOW_RANDOM_HPP_H
#define __CONTROL_FLOW_RANDOM_HPP_H

#ifndef CONTROL_FLOW_RANDOM_HPP_H
#define CONTROL_FLOW_RANDOM_HPP_H

void run_random_numbers();

#endif  // CONTROL_FLOW_RANDOM_HPP_H

#endif  // __CONTROL_FLOW_RANDOM_HPP_H
